### PR TITLE
change version info from x.y.z-a to x.y.z

### PR DESCRIPTION
**Pull request by jason-wytist**
change version info from x.y.z-a to x.y.z .
before testing, make symbolic links like below.
x is a integer number

````
$ cd /Applications
$ ln -s /Applications/mampstack-5.6.19-x ./mampstack-5.6.19
$ ln -s /Applications/mampstack-7.0.14-x ./mampstack-7.0.14
````

### CODE REVIEW

**Comment by jason-wytist** [comment]
checklist

- [x] mamp-current command is working good.
- [x] mamp-ctl-5.6.19 is working good.
- [x] mamp-status-5.6.19 is working good.
- [x] mamp-cli-on-5.6.19 is working good.
- [x] mamp-cli-off-5.6.19 is working good.
- [x] mamp-ctl-7.0.14 is working good.
- [x] mamp-status-7.0.14 is working good.
- [x] mamp-cli-on-7.0.14 is working good.
- [x] mamp-cli-off 7.0.14 is working good.

**Comment by jason-wytist** [comment]
~~mamp-status-7.0.14 is not working now.~~
~~i must fix it.~~

i fixed it on https://github.com/wytist/wytist-dev-scripts/pull/5/commits/4958fe8cf20b4556e90d5380a3da14c94c0185bf

**Comment by jason-wytist** [comment]
@choiminyeong 

please, cross-check and write checklist for me.

**Comment by jobchoi** [comment]
checklist

 - ~~[ ] mamp-current command is working good.~~
 - ~~[ ] mamp-ctl-5.6.19 command is working good.~~
 - ~~[ ] mamp-status-5.6.19 command is working good.~~
 - ~~[ ] mamp-cli-on-5.6.19 command is working good.~~
 - ~~[ ] mamp-cli-off-5.6.19 command is working good.~~
 - ~~[ ] mamp-current command is working good.~~
 - ~~[ ] mamp-ctl-5.6.29 command is working good.~~
 - ~~[ ] mamp-status-5.6.29 command is working good.~~
 - ~~[ ] mamp-cli-on-5.6.29 command is working good.~~
 - ~~[ ] mamp-cli-off-5.6.29 command is working good.~~
 - ~~[ ] mamp-ctl-7.0.14 command is working good.~~
 - ~~[ ] mamp-status-7.0.14 command is working good.~~
 - ~~[ ] mamp-cli-on-7.0.14 command is working good.~~
 - ~~[ ] mamp-cli-off 7.0.14 command is working good.~~

**Comment by jobchoi** [comment]
@JoonSooHa 
mamp현재 배포 버전이 5.6.29이며 5.6.19는 배포되지 않습니다.
스크립트를 5.6.29버전으로 변경해서 테스트 해야합니다.

**Comment by jason-wytist** [comment]
@choiminyeong 
말씀하신대로 mamp-5.6.29로 변경하도록 하겠습니다.

**Pull request merged**
